### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by altoms** [illuZion9999/Rzy-Protector-V2-unpacker#1]
when i drag the .exe to the unpacker 
its always shows
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Rzy_Protector_V2_Unpacker.Protections.Empty_Types.Execute(ModuleDefMD module) in C:\Users\altom\Desktop\Tools baru\Rzy-Protector-V2-unpacker-master\Rzy Protector V2 Unpacker\Protections\Empty Types.cs:line 24
   at Rzy_Protector_V2_Unpacker.Program.Main(String[] args) in C:\Users\altom\Desktop\Tools baru\Rzy-Protector-V2-unpacker-master\Rzy Protector V2 Unpacker\Program.cs:line 45

how can i fix it ?

**Comment by illuZion9999** [comment]
Hello, could you please send me the file that makes the unpacker crash?

**Comment by altoms** [comment]
i just drag any protector to the unpacker 
and always got that error

**Comment by altoms** [comment]
so how to remove unhandled exception error 
so when i drag it 
it will bypassed automaticly

**Comment by illuZion9999** [comment]
For me it works fine, please send a file for which it throws the exception.

**Comment by altoms** [comment]
https://cdn.discordapp.com/attachments/681332596604534850/701776697753600040/APABGnew_protected.exe

**Comment by illuZion9999** [comment]
Issue is fixed.
