### ISSUE TITLE
Unhandled Exception Error

### ISSUE THREAD

**Issue by Hookahice** [illuZion9999/Rzy-Protector-V2-unpacker#5]
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Rzy_Protector_V2_Unpacker.Protections.ConstantsMutate.Execute(ModuleDefMD module)
   at Rzy_Protector_V2_Unpacker.Program.Main(String[] args)

Test file: https://www.mediafire.com/file/h0ge7xnlcua952p/Testing_Rzy.rar/file

**Comment by Spx12x** [comment]
@Hookahice  Not Rzy Protector, it's Prab's old Protector: https://github.com/rvrsh3ll/SkiDzEX{He deleted it, this is a fork of it by someone else}
